version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/src/DeltaLakeSharp.Server/v3"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
