<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.DI.DeltaTableService.Adbc</RootNamespace>
    <AssemblyName>Microsoft.DI.DeltaTableService.Adbc</AssemblyName>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\DeltaTableService.Client\DeltaTableService.Client.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Arrow" Version="22.1.0" />
    <PackageReference Include="Apache.Arrow.Adbc" Version="0.22.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.9" />
    <PackageReference Include="System.Text.Json" Version="9.0.9" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeltaTableService.Client\DeltaTableService.Client.csproj"
                      AdditionalProperties="RustTargetCpu=$(RustTargetCpu)" />
  </ItemGroup>
</Project>
